export default [
  {
    cateName: "行业医疗",
    list: [
      { value: "iconfont icon-yiyuan3" },
      { value: "iconfont icon-yiyuan4" },
      { value: "iconfont icon-yiyuan5" },
      { value: "iconfont icon-yiyuan1" },
      { value: "iconfont icon-yiyuan" },
      { value: "iconfont icon-yiyuan2" },
      { value: "iconfont icon-yiliaowenzhen" },
      { value: "iconfont icon-yisheng1" },
      { value: "iconfont icon-yisheng2" },
      { value: "iconfont icon-yisheng4" },
      { value: "iconfont icon-yiliao1" },
      { value: "iconfont icon-yisheng" },
      { value: "iconfont icon-hushi3" },
      { value: "iconfont icon-icon_hushi" },
      { value: "iconfont icon-hushi" },
      { value: "iconfont icon-hushi1" },
      { value: "iconfont icon-yiliao-" },
      { value: "iconfont icon-yiliao-1" },
      { value: "iconfont icon-yibaokongfeisvg-" },
      { value: "iconfont icon-ziyuan" },
      { value: "iconfont icon-bingchuangsvg" },
      { value: "iconfont icon-bingchuang1" },
      { value: "iconfont icon-yiliao21" },
      { value: "iconfont icon-yiliaoshebei" },
      { value: "iconfont icon-yiliao23" },
      { value: "iconfont icon-bingchuang2" },
      { value: "iconfont icon-shangyeweixuanzhong" },
      { value: "iconfont icon-yiliaodangan" },
      { value: "iconfont icon-bingchuang3" },
      { value: "iconfont icon-bingchuang4" },
      { value: "iconfont icon-yiliao" },
      { value: "iconfont icon-73316" },
      { value: "iconfont icon-yiliaoqixie" },
      { value: "iconfont icon-yiliao-copy" },
      { value: "iconfont icon-tel" },
      { value: "iconfont icon-yiliao3" },
      { value: "iconfont icon-yiliao4" },
      { value: "iconfont icon-yiliao5" },
      { value: "iconfont icon-yiliao6" },
      { value: "iconfont icon-yiliao7" },
      { value: "iconfont icon-bingchuangzhouzhuantongji" },
      { value: "iconfont icon-yiliao8" },
      { value: "iconfont icon-yiliao9" },
      { value: "iconfont icon-yiliao10" },
      { value: "iconfont icon-yiliaobaoxian" },
      { value: "iconfont icon-jiuhuche" },
      { value: "iconfont icon-yiliao12" },
      { value: "iconfont icon-yiliao13" },
      { value: "iconfont icon-yiliao14" },
      { value: "iconfont icon-yiliao15" },
      { value: "iconfont icon-yiliao16" },
      { value: "iconfont icon-yiliao17" },
      { value: "iconfont icon-yiliaoqixie1" },
      { value: "iconfont icon-dazhen" },
      { value: "iconfont icon-dazhen1" },
      { value: "iconfont icon-dazhen2" },
      { value: "iconfont icon--dazhen" },
      { value: "iconfont icon-yaowuku" },
      { value: "iconfont icon-tubiao-pian_yaowu" },
      { value: "iconfont icon-baogao" },
      { value: "iconfont icon-yaowulinchuangshiyanfuwu" },
      { value: "iconfont icon-yaowulinchuangshiyan" },
      { value: "iconfont icon-drug-full" },
      { value: "iconfont icon-drug" },
      { value: "iconfont icon-yaowu1" },
      { value: "iconfont icon-yaowu" },
      { value: "iconfont icon-yaowulinchuang" },
      { value: "iconfont icon-yaowufenfa" },
      { value: "iconfont icon-yaowuguanli" },
      { value: "iconfont icon-yiliao11" },
      { value: "iconfont icon-shoushu" },
      { value: "iconfont icon-shoushu1" },
      { value: "iconfont icon-shoushu2" },
      { value: "iconfont icon-shoushu3" },
      { value: "iconfont icon-shoushu4" },
      { value: "iconfont icon-shoushu5" },
      { value: "iconfont icon-shoushu6" },
      { value: "iconfont icon-zhifu2" },
      { value: "iconfont icon-zhifu5" },
      { value: "iconfont icon-zhifu4" }
    ]
  },
  {
    cateName: "用户操作",
    list: [
      { value: "el-icon-delete-solid" },
      { value: "el-icon-delete" },
      { value: "el-icon-s-tools" },
      { value: "el-icon-setting" },
      { value: "el-icon-user-solid" },
      { value: "el-icon-s-custom" },
      { value: "el-icon-user" },
      { value: "el-icon-rank" },
      { value: "el-icon-refresh" },
      { value: "el-icon-refresh-left" },
      { value: "el-icon-refresh-right" },
      { value: "el-icon-zoom-in" },
      { value: "el-icon-zoom-out" },
      { value: "el-icon-remove-outline" },
      { value: "el-icon-circle-plus-outline" },
      { value: "el-icon-circle-check" },
      { value: "el-icon-circle-close" },
      { value: "el-icon-minus" },
      { value: "el-icon-plus" },
      { value: "el-icon-check" },
      { value: "el-icon-close" },
      { value: "el-icon-upload" },
      { value: "el-icon-upload2" },
      { value: "el-icon-download" },
      { value: "el-icon-s-comment" },
      { value: "el-icon-share" },
      { value: "el-icon-edit" },
      { value: "el-icon-edit-outline" },
      { value: "el-icon-folder-add" },
      { value: "el-icon-folder-remove" },
      { value: "el-icon-document-copy" },
      { value: "el-icon-document-checked" },
      { value: "el-icon-document" },
      { value: "fa fa-plus-square-o" },
      { value: "fa fa-plus-square" },
      { value: "fa fa-minus-square" },
      { value: "fa fa-minus-square-o" },
      { value: "fa fa-check" },
      { value: "fa fa-check-circle" },
      { value: "fa fa-check-square" },
      { value: "fa fa-check-square-o" },
      { value: "fa fa-wrench" }
    ]
  },
  {
    cateName: "web应用",
    list: [
      { value: "fa fa-envelope-open" },
      { value: "fa fa-envelope-open-o" },
      { value: "fa fa-address-book" },
      { value: "fa fa-address-book-o" },
      { value: "fa fa-ban" },
      { value: "fa fa-bluetooth" },
      { value: "fa fa-bluetooth-b" },
      { value: "fa fa-file-image-o" },
      { value: "fa fa-file-archive-o" },
      { value: "fa fa-file-audio-o" },
      { value: "fa fa-file-movie-o" },
      { value: "fa fa-gears" },
      { value: "fa fa-comments" },
      { value: "fa fa-folder-open-o" },
      { value: "fa fa-folder-o" },
      { value: "fa fa-mail-forward" },
      { value: "fa fa-key" },
      { value: "fa fa-lock" },
      { value: "fa fa-unlock-alt" },
      { value: "fa fa-unlock" },
      { value: "fa fa-photo" },
      { value: "fa fa-warning" },
      { value: "fa fa-code" },
      { value: "fa fa-code-fork" },
      { value: "fa fa-star" },
      { value: "fa fa-star-half-o" },
      { value: "fa fa-wrench" },
      { value: "fa fa-thumbs-o-up" },
      { value: "fa fa-thumbs-up" },
      { value: "fa fa-thumbs-down" },
      { value: "fa fa-thumbs-o-down" },
      { value: "fa fa-mars" },
      { value: "fa fa-venus" },
      { value: "iconfont icon-zhifu" },
      { value: "iconfont icon-zhifu3" },
      { value: "iconfont icon-zhifubao" },
      { value: "iconfont icon-zhifu1" },
      { value: "iconfont icon-zhifu4" },
      { value: "iconfont icon-zhifu5" },
      { value: "iconfont icon-zhifu2" }
    ]
  },
  {
    cateName: "方向与箭头",
    list: [
      { value: "el-icon-d-caret" },
      { value: "el-icon-caret-left" },
      { value: "el-icon-caret-right" },
      { value: "el-icon-caret-bottom" },
      { value: "el-icon-caret-top" },
      { value: "el-icon-bottom-left" },
      { value: "el-icon-bottom-right" },
      { value: "el-icon-back" },
      { value: "el-icon-right" },
      { value: "el-icon-bottom" },
      { value: "el-icon-top" },
      { value: "el-icon-top-left" },
      { value: "el-icon-top-right" },
      { value: "el-icon-arrow-left" },
      { value: "el-icon-arrow-right" },
      { value: "el-icon-arrow-down" },
      { value: "el-icon-arrow-up" },
      { value: "el-icon-d-arrow-left" },
      { value: "el-icon-d-arrow-right" },
      { value: "el-icon-sort" },
      { value: "el-icon-sort-up" },
      { value: "el-icon-sort-down" },
      { value: "fa fa-arrows-h" },
      { value: "fa fa-arrows-v" },
      { value: "fa fa-mail-reply" },
      { value: "fa fa-mail-reply-all" },
      { value: "fa fa-mail-forward" },
      { value: "fa fa-level-down" },
      { value: "fa fa-level-up" },
      { value: "fa fa-arrow-circle-down" },
      { value: "fa fa-arrow-circle-left" },
      { value: "fa fa-arrow-circle-o-down" },
      { value: "fa fa-arrow-circle-o-left" },
      { value: "fa fa-chevron-circle-down" },
      { value: "fa fa-chevron-circle-left" },
      { value: "fa fa-chevron-circle-right" },
      { value: "fa fa-chevron-circle-up" }
    ]
  },
  {
    cateName: "交通与建筑",
    list: [
      { value: "iconfont icon-jianzhu_huaban" },
      { value: "iconfont icon-weibiaoti--" },
      { value: "iconfont icon-jiaotong" },
      { value: "iconfont icon-jiaotong1" },
      { value: "iconfont icon-jiaotong3" },
      { value: "iconfont icon-jiaotong4" },
      { value: "iconfont icon-jiaotong5" },
      { value: "iconfont icon-jiaotong6" },
      { value: "iconfont icon-jiaotong7" },
      { value: "iconfont icon-jiaotong8" },
      { value: "iconfont icon-jiaotong9" },
      { value: "iconfont icon-jiaotong10" },
      { value: "iconfont icon-jiaotong11" },
      { value: "iconfont icon-jiaotong12" },
      { value: "iconfont icon-jianzhu" },
      { value: "iconfont icon-jianzhu1" },
      { value: "iconfont icon-jianzhu2" },
      { value: "iconfont icon-jianzhu3" },
      { value: "iconfont icon-i-architecture" },
      { value: "iconfont icon-jianzhu5" },
      { value: "iconfont icon-jianzhu6" },
      { value: "iconfont icon-jianzhu7" },
      { value: "iconfont icon-jianzhu8" },
      { value: "iconfont icon-jianzhu9" },
      { value: "iconfont icon-jiaotongtingchechangxianxing" },
      { value: "fa fa-automobile" },
      { value: "fa fa-rocket" },
      { value: "fa fa-cab" },
      { value: "fa fa-plane" },
      { value: "fa fa-subway" },
      { value: "fa fa-motorcycle" },
      { value: "fa fa-truck" },
      { value: "fa fa-bus" },
      { value: "fa fa-bicycle" },
      { value: "fa fa-ship" }
    ]
  },
  {
    cateName: "媒体播放",
    list: [
      { value: "iconfont icon-meiti9" },
      { value: "iconfont icon-yinyue1" },
      { value: "iconfont icon-erjiyuyin" },
      { value: "iconfont icon-erji1" },
      { value: "iconfont icon-meiti11" },
      { value: "iconfont icon-erji2" },
      { value: "iconfont icon-meiti10" },
      { value: "iconfont icon-erji" },
      { value: "iconfont icon-meiti" },
      { value: "iconfont icon-huatong" },
      { value: "iconfont icon-meiti6" },
      { value: "iconfont icon-shipin" },
      { value: "iconfont icon-meiti8" },
      { value: "iconfont icon-meiti7" },
      { value: "iconfont icon-yinyue" },
      { value: "iconfont icon-meiti5" },
      { value: "iconfont icon-meiti4" },
      { value: "iconfont icon-meiti3" },
      { value: "iconfont icon-meiti2" },
      { value: "el-icon-video-pause" },
      { value: "el-icon-video-play" },
      { value: "el-icon-camera-solid" },
      { value: "el-icon-camera" }
    ]
  },
  {
    cateName: "LOGO与标志",
    list: [
      { value: "fa fa-android" },
      { value: "fa fa-apple" },
      { value: "fa fa-bitcoin" },
      { value: "fa fa-bluetooth" },
      { value: "fa fa-bluetooth-b" },
      { value: "fa fa-chrome" },
      { value: "fa fa-css3" },
      { value: "fa fa-edge" },
      { value: "fa fa-facebook" },
      { value: "fa fa-facebook-official" },
      { value: "fa fa-firefox" },
      { value: "fa fa-git" },
      { value: "fa fa-git-square" },
      { value: "fa fa-gitlab" },
      { value: "fa fa-github" },
      { value: "fa fa-internet-explorer" },
      { value: "fa fa-paypal" },
      { value: "fa fa-qq" },
      { value: "fa fa-weixin" },
      { value: "fa fa-weibo" },
      { value: "fa fa-windows" },
      { value: "fa fa-twitter-square" },
      { value: "fa fa-twitter" },
      { value: "iconfont icon-zhifu" },
      { value: "iconfont icon-zhifu3" },
      { value: "iconfont icon-zhifubao" }
    ]
  },
  {
    cateName: "设备与技术",
    list: [
      { value: "iconfont icon-Upan1" },
      { value: "iconfont icon-luyouqi2" },
      { value: "iconfont icon-shujuku2" },
      { value: "iconfont icon-shujuku3" },
      { value: "iconfont icon-shujuku4" },
      { value: "iconfont icon-WIFIwofi" },
      { value: "iconfont icon-xinpian2" },
      { value: "iconfont icon-xinpian3" },
      { value: "iconfont icon-dianhua2" },
      { value: "iconfont icon-erji1" },
      { value: "iconfont icon-erji2" },
      { value: "iconfont icon-meiti11" },
      { value: "iconfont icon-luyouqi3" },
      { value: "iconfont icon-yiliao21" },
      { value: "iconfont icon-shujuku5" },
      { value: "iconfont icon-shujuku41" },
      { value: "iconfont icon-luyouqi" },
      { value: "iconfont icon-diannao" },
      { value: "iconfont icon-shujuku" },
      { value: "iconfont icon-diannao1" },
      { value: "iconfont icon-diannao2" },
      { value: "iconfont icon-jiaohuanji" },
      { value: "iconfont icon-jiaohuanji1" },
      { value: "iconfont icon-xinpian1" },
      { value: "iconfont icon-xinpian" },
      { value: "iconfont icon-jiaohuanji2" },
      { value: "iconfont icon-meiti4" },
      { value: "iconfont icon-icon-test1" },
      { value: "iconfont icon-meiti6" },
      { value: "iconfont icon-Upan" },
      { value: "iconfont icon-luyouqicopy" }
    ]
  },
  {
    cateName: "动画与旋转",
    list: [
      { value: "fa fa-spinner fa-spin" },
      { value: "fa fa-circle-o-notch fa-spin" },
      { value: "fa fa-refresh fa-spin" },
      { value: "fa fa-cog fa-spin" },
      { value: "fa fa-cog fa-spin" }
    ]
  }
];
